
import { OnboardingStep } from "./types";

export const onboardingSteps: OnboardingStep[] = [
  {
    id: "situation",
    title: "Which best describes your current situation?",
    type: "single-select",
    options: [
      { id: "job_searching", label: "Looking for a new job" },
      { id: "exploring", label: "Just exploring" },
      { id: "midcareer_stuck", label: "Feeling stuck mid-career" },
      { id: "military", label: "Translating military experience" },
      { id: "career_change", label: "Switching careers or industries" },
      { id: "resume_building", label: "Just want a better resume" },
    ],
  },
  {
    id: "role",
    title: "What's your current or most recent role?",
    type: "multi-select",
    options: [
      { id: "software_engineer", label: "Software Engineer" },
      { id: "product_manager", label: "Product Manager" },
      { id: "data_analyst", label: "Data Analyst" },
      { id: "marketing_manager", label: "Marketing Manager" },
      { id: "sales_rep", label: "Sales Representative" },
      { id: "designer", label: "Designer" },
      { id: "project_manager", label: "Project Manager" },
      { id: "consultant", label: "Consultant" },
      { id: "operations", label: "Operations" },
      { id: "finance", label: "Finance" },
      { id: "hr", label: "Human Resources" },
      { id: "customer_success", label: "Customer Success" },
      { id: "military", label: "Military" },
      { id: "other", label: "Other" },
    ],
  },
  {
    id: "industry",
    title: "What industries have you worked in?",
    type: "multi-select",
    options: [
      { id: "technology", label: "Technology" },
      { id: "finance", label: "Finance" },
      { id: "healthcare", label: "Healthcare" },
      { id: "education", label: "Education" },
      { id: "retail", label: "Retail" },
      { id: "manufacturing", label: "Manufacturing" },
      { id: "consulting", label: "Consulting" },
      { id: "nonprofit", label: "Non-profit" },
      { id: "government", label: "Government" },
      { id: "military", label: "Military" },
      { id: "startup", label: "Startup" },
      { id: "enterprise", label: "Enterprise" },
      { id: "media", label: "Media & Entertainment" },
      { id: "other", label: "Other" },
    ],
  },
  {
    id: "pain",
    title: "What's your biggest challenge right now?",
    type: "single-select",
    options: [
      { id: "resume_confusion", label: "Not sure what to include on my resume" },
      { id: "explaining_background", label: "Hard to explain my background" },
      { id: "military_translation", label: "Translating military or technical experience" },
      { id: "no_fit", label: "Can't find roles that feel like a good fit" },
      { id: "too_much_effort", label: "Too time-consuming to apply" },
      { id: "lost", label: "I don't know what I'm looking for" },
    ],
  },
  {
    id: "goals",
    title: "What do you want help with?",
    type: "multi-select",
    options: [
      { id: "find_roles", label: "Figure out what roles I'm qualified for" },
      { id: "build_resume", label: "Generate a tailored resume" },
      { id: "career_story", label: "Tell my career story better" },
      { id: "apply_better", label: "Apply to better-fit jobs" },
      { id: "talk_it_out", label: "Talk through my experience" },
      { id: "linkedin", label: "Build a better LinkedIn" },
      { id: "something_else", label: "Something else" },
    ],
  },
];
