// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://deofbwuazrvpocyybjpl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlb2Zid3VhenJ2cG9jeXlianBsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMDczMTUsImV4cCI6MjA2NTY4MzMxNX0.f2QvutjcUSdciuAZOwNaFd28xsS95rU3JSYo0BAHaNI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);